### ISSUE TITLE
Uncaught Exception for error response in sendMessage

### ISSUE THREAD

**Issue by jpradeep2003** [plivo/plivo-java#29]
The error response is not properly handled. 
The following exception is thrown. 
Since my account was disabled, the API is probably returning an error response. However, this client code is not handling that gracefully. Instead, it throws an uncaught exception.

com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 6
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:176)
        at com.google.gson.Gson.fromJson(Gson.java:795)
        at com.google.gson.Gson.fromJson(Gson.java:761)
        at com.google.gson.Gson.fromJson(Gson.java:710)
        at com.google.gson.Gson.fromJson(Gson.java:682)
        at com.plivo.helper.api.client.RestAPI.sendMessage(RestAPI.java:530)
	<<application code...>>

**Comment by hm4rk** [comment]
Upvote. The error handling must be improved.

**Comment by plivo-sdks** [comment]
Fixed in v4.
