### ISSUE TITLE
NoSuchFieldError: SNAKE_CASE

### ISSUE THREAD

**Issue by AaronSuAu** [plivo/plivo-java#34]
Hi,
    All I did is: 
     Plivo.init("auth_id", "auth_token");
    But it gives me this error:
Exception in thread "main" java.lang.NoSuchFieldError: SNAKE_CASE
	at com.plivo.api.PlivoClient.<clinit>(PlivoClient.java:68)
	at com.plivo.api.Plivo.init(Plivo.java:11)
	at com.plivo.api.Plivo.init(Plivo.java:20)
	at message.PlivoSMSNew.main(PlivoSMSNew.java:12)
It is true that I can't find SNAKE_CASE in PliveClient.java file. wondering how to solve it.

**Comment by plivo-sdks** [comment]
@AaronSuAu Seems like this is an issue caused by a stale version of Jackson.

`SNAKE_CASE` is accessed via `com.fasterxml.jackson.databind.PropertyNamingStrategy`. Can you confirm the version of FasterXML/Jackson you are using?

**Comment by AaronSuAu** [comment]
Hi,
    I guess that's the reason as I didn't use this package. Thanks.
